# Site settings
author: Jessica Gladstone
title: Full Stack Web Development
header-img: img/home-bg.png
email: jcg321@comcast.net
copyright_name: Jessica Gladstone
description: > # this means to ignore newlines until "baseurl:"
  Observations in Web Dev
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Jcg408

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
